---
- hosts: all
  tasks: 
   - name: Create an ubuntu container
     command: docker run -d --name web ubuntu /bin/bash


   - name: add container to inventory
     add_host:
       name: web
       ansible_connection: docker
     changed_when: false

   - name: run command in container
     delegate_to: web
     raw: /proc/cpuinfo

