---
- hosts: all
  tasks: 
   - name: Create a centos container
     docker_container:
       name: web
       image: centos:7
       detach: yes
       tty: yes

   - name: add container to inventory
     add_host:
       name: web
       ansible_connection: docker
     changed_when: false

   - name: run command in container
     delegate_to: web
     raw: yum -y update && yum install -y python

   - name: run df command in container
     delegate_to: web
     command: df -h
     register: result
   - name: Print df value
     debug: msg="value {{ result.stdout }}"
