---
- hosts: all
  become: true
  tasks:
   - name: Delete container
     docker_container:
       name: web
       state: absent
     ignore_errors: yes
   - name: Create a centos container
     docker_container:
       name: web
       image: centos:7
       detach: yes
       tty: yes

   - name: add container to inventory
     add_host:
       name: container_web
       ansible_connection: docker
       ansible_user: root
     changed_when: false

   - name: run command in container
     delegate_to: container_web
     raw: yum -y update && yum install -y python && yum -y install git

   - name: run git command in container
     delegate_to: web
     command: git --version
     register: result
   - name: Print git version
     debug: msg="{{ result.stdout }}"
